# Generated by Django 3.1.2 on 2020-10-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password1',
            field=models.CharField(error_messages={'not_same': 'Le due password non corrispondono!!'}, max_length=50),
        ),
    ]
