# Generated by Django 3.1.2 on 2020-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201029_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default='dishes/no-image-1771002-1505134.png', null=True, upload_to='dishes'),
        ),
    ]
