# Generated by Django 3.1.2 on 2020-11-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201106_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, default='dishes/no-image-1771002-1505134.png', null=True, upload_to='dishes'),
        ),
    ]
