# Generated by Django 3.1.2 on 2020-11-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201109_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='litri',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
