# Generated by Django 3.1.2 on 2020-11-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201112_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(default='', max_length=35, verbose_name='Regione'),
        ),
    ]
