# Generated by Django 3.1.2 on 2020-10-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
        migrations.AddField(
            model_name='table',
            name='reservation_last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='table',
            name='reservation_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
