# Generated by Django 3.1.2 on 2020-10-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='città',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='n_civico',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='provincia',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='regione',
            new_name='region',
        ),
    ]
