# Generated by Django 3.1.2 on 2020-10-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201022_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restaurate',
            field=models.BooleanField(default=False),
        ),
    ]
