# Generated by Django 3.1.2 on 2020-10-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201030_1056'),
        ('users', '0005_auto_20201030_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeAway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overprice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drink', models.ManyToManyField(to='products.Drink')),
                ('food', models.ManyToManyField(to='products.Food')),
            ],
        ),
    ]
