# Generated by Django 3.1.2 on 2020-11-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201112_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='n_people',
            field=models.PositiveIntegerField(),
        ),
    ]
