# Generated by Django 3.1.2 on 2020-10-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_restaurate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_restaurate',
            new_name='is_restaurateur',
        ),
    ]
