# Generated by Django 3.1.2 on 2020-11-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0007_auto_20201112_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='drink',
            field=models.ManyToManyField(help_text='<em>Tenere premuto Ctrl per selezionare più prodotti</em>', to='products.Drink'),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='food',
            field=models.ManyToManyField(help_text='<em>Tenere premuto Ctrl per selezionare più prodotti</em>', to='products.Food'),
        ),
    ]
