# Generated by Django 3.1.2 on 2020-10-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_takeaway_overprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeaway',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=4),
            preserve_default=False,
        ),
    ]
