# Generated by Django 3.1.2 on 2020-10-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201030_1056'),
        ('users', '0008_takeaway_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='drink',
            field=models.ManyToManyField(help_text='<em>Tenere premuto Ctrl per selezionare più prodotti</em>', to='products.Drink'),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='food',
            field=models.ManyToManyField(help_text='<em>Tenere premuto Ctrl per selezionare più prodotti</em>', to='products.Food'),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
    ]
