# Generated by Django 3.1.2 on 2020-11-04 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201104_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeaway',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takeaways', to=settings.AUTH_USER_MODEL),
        ),
    ]
