# Generated by Django 3.1.2 on 2020-11-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201104_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note:'),
        ),
    ]
