# Generated by Django 3.1.2 on 2020-11-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20201106_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
